// <auto-generated />
namespace ExemploEFCodeFirst.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AdicionadoOModeloPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicionadoOModeloPost));
        
        string IMigrationMetadata.Id
        {
            get { return "201208250555577_AdicionadoOModeloPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
